version: '3.1'

services:
  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    ports:
    - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  adminer:
    image: adminer:4.7.7
    restart: always
    environment:
      ADMINER_DESIGN: galkaev
    ports:
      - 8080:8080
    depends_on:
      - db

  cache:
    image: redis:6.0.8-alpine3.12
    restart: unless-stopped
    ports:
    - 6379:6379

  backend:
    build:
      context: '.'
      dockerfile: 'dev/Dockerfile'
    ports:
      - 8080:8080
    volumes:
      - ./src:/digis-test/src
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=password
      - CACHE_HOST=cache
      - CACHE_PORT=6379

  migrations:
    entrypoint: yarn
    command: run typeorm migration:run
    build:
      context: '.'
      dockerfile: 'dev/Dockerfile'
    volumes:
      - ./src:/digis-test/src
      - ./migrations:/digis-test/migrations
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=password
      - CACHE_HOST=cache
      - CACHE_PORT=6379
